---
    - include_tasks: pg_install.yml

    - include_tasks: pg_move_data_dir.yml
      when: 'not "/var/lib/postgresql/" in db_data_dir'

    - include_tasks: pg_config.yml

    - include_tasks: pg_backup.yml

