---

    - name: config | ensure bin dir existis
      file:
        path: "{{ db_bin_dir }}"
        owner: postgres
        group: postgres
        mode: 0700
        state: directory

    - name: config | ensure log dir existis
      file:
        path: "{{ db_log_dir }}"
        owner: root
        group: postgres
        mode: 0770
        state: directory

    - name: config | conf.d for shared config
      template:
        src: 00shared.conf.j2
        dest: /etc/postgresql/{{ postgres_version }}/main/conf.d/00shared.conf
        owner: postgres
        group: postgres
        mode: 0600
      notify:
         - restart postgres

    - name: config | conf.d for logging config
      template:
        src: 01log.conf.j2
        dest: /etc/postgresql/{{ postgres_version }}/main/conf.d/01log.conf
        owner: postgres
        group: postgres
        mode: 0600
      notify:
         - restart postgres

    - name: config access | allow login from other hosts
      lineinfile:
        path: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
        line: "host    all             all             all            md5"
      notify:
         - restart postgres

    - name: config | copy cleanup log script
      template:
        src: cronjob_cleanup_log.sh.j2
        dest: "{{ db_bin_dir }}/cleanup_log.sh"
        owner: postgres
        group: postgres
        #group: www-data
        mode: 0774
      tags:
          - copy_script

    - name: config | set cleanup cronjob run daily
      cron:
        name: cleanup logs older than {{ db_log_retention_in_days }}
        user: postgres
        special_time: daily
        state: present
        job: "{{ db_bin_dir }}/cleanup_log.sh 2>&1 | logger -t '[log cleanup]'"
