---

    - name: move data | ensure service is NOT running but enabled
      service:
        name: postgresql
        state: stopped
        enabled: yes

    # move postgres data directory
    # https://www.digitalocean.com/community/tutorials/how-to-move-a-postgresql-data-directory-to-a-new-location-on-ubuntu-16-04
    - name: move data | check if already moved dir
      stat:
        path: /var/lib/postgresql/{{ postgres_version }}/main.bak
      register: result

    - name: move data | ensure data dir existis
      file:
        path: "{{ db_data_dir }}"
        owner: postgres
        group: postgres
        mode: 0700
        state: directory
      when: result.stat.exists == False

    - name: move data | rsync data from default location to new data_dir
      synchronize:
        src: "/var/lib/postgresql/{{ postgres_version }}/main/"
        dest: "{{ db_data_dir }}"
      delegate_to: "{{ inventory_hostname }}"
      when: result.stat.exists == False

    - name: move data | rename old data_dir
      command: >
        mv /var/lib/postgresql/{{ postgres_version }}/main
            /var/lib/postgresql/{{ postgres_version }}/main.bak
      when: result.stat.exists == False

